# Questions:
a. How to properly evaluate the performance of affiliates from perspective of our company?

b. Which affiliates are not profitable? Which affiliates should we continue to work with?

# Summary:

In order to find out which affiliate performs better than others I decided to seperate all the affiliates into 3 layers: affiliates of the 3rd layer were attracted by affiliates of the 2nd layer, affiliates of the 2nd layer were attracted by affiliates of the 1st layer. 
After this we can see detailed relationships between affiliates. 


<br>Top 4 users:

1) <b>c52d9139a2</b> with 309 875.35 RUB (\~15% of the total income), where 39 956.47 RUB brought by him and 269 918.88 RUB by users he attracted. This user attracted 367 new users.

2) <b>a3ae3125fe</b> with 300 404.08 RUB (\~14% of the total income), where 210 044.33 RUB brought by him and 90 359.75 RUB by users he attracted. This user attracted 99 new users, among them are 2 affiliates: <u>d20a2ac474</u> and <u>3f61a9c4bf</u>, which brought him 42 617.47 RUB in total.

3) <b>a12f7b9ea8</b> with 224 710.30 RUB (\~11% of the total income), where 192 575.29 RUB brought by him and 32 135.01 RUB by users he attracted. This user attracted 67 new users.

4) <b>3edee82c4b</b> with 180 279.42 RUB (\~9% of the total income), where 37 916.00 RUB broght by him and 142 363.42 RUB by users he attracted. This user attracted 424 new users, among them there are 2 affiliates: <u>f0e3b2548a</u> and <u>6f77ad82a7</u>, which brought him 75 344.99 RUB in total.

<br>Top 5 "worst" affiliates:


1) <b>020d1cb3a9</b>. This affiliate still didn't pay for his ride and brought just 1 users, which also still didn't pay for his ride.

2) <b>96f303087b</b>. This affiliate made just 1 order, brought 94,24 RUB and didn't attract anybody.

3) <b>4907b9bf1f</b>. This affiliate made just 2 orders, brought 158,13 RUB and didn't attract anybody.

4) <b>9da3ef9af1</b>. This affiliate made just 1 order, brought 258,82 RUB and didn't attract anybody.

5) <b>f852e0a44d</b>. This affiliate made just 2 orders, brought 387,48 RUB and attracted 3 users, which still didn't pay for their rides.

<br>We also can see, that affiliates of the 2nd layer performed better than some of the 1st layer => they didn' appear in Top 5 "worst" affiliates. 
There is affiliate of the 3rd layer, which perfomed better than some of the 1st layer, this affiliate, under id <u>00143ea850</u>, attracted 4 149,69 RUB for us, though we didn't earned directly from this affiliate.

# Code:

In [1]:
import pandas as pd
from IPython.display import display_html, display

pd.set_option('display.max_columns', None)

In [2]:
orders = pd.read_csv('data/orders_task3.csv')
promocodes = pd.read_csv('data/promocodes_task3.csv')
users = pd.read_csv('data/users_task3.csv')

In [3]:
# creating df of user_ids where roles == 'affiliate'

df = users.loc[users.roles == "['affiliate']"].drop(['roles'], axis=1)

# merging promocodes df

df = df.merge(promocodes, on='user_id', how='left')

In [4]:
df.head()

      user_id      utm_c       code
0  d891c8305a  9cd0f2632  73a24f3d1
1  f94d3de761  afd8c7e77  0f87d693a
2  b1a6cf0230  8354af4ab  41c191655
3  e7717637a4  85fc32ec2  155c55d39
4  d774d65c49  85fc32ec2  5907960e6

We have affiliates which attracted other affiliates. 
Now we build the 1st and the 2nd layers of affiliates:
- Affiliates of the 1st layer are not attracted by any other affiliate.
- Affiliates of the 2nd layer are attracted by affiliates from the 1st layer.

In [5]:
# building the dataframes with 1st and the 2nd layers of affiliates

first_users = df
second_users = pd.DataFrame()

for c in first_users.code:
    if first_users.utm_c.isin([c]).any():
        second_users = second_users.append(first_users.loc[first_users.utm_c == c])
        first_users = first_users.loc[first_users.utm_c != c]

There are 2 affiliates in the 2nd layer, which are attracted by other afilliates from the 2nd layer:

In [6]:
for c in second_users.code:
    if second_users.utm_c.isin([c]).any():
        print(c)

75b759c38
0c481c232

Creating third_users df, which contains afilliates attracted by afilliates from the 2nd layer.

Removing afilliates from 2nd layer which are in the 3rd layer:

In [7]:
third_users = pd.DataFrame()

for c in second_users.code:
    if second_users.utm_c.isin([c]).any():
        third_users = third_users.append(second_users.loc[second_users.utm_c == c])
        second_users = second_users.loc[second_users.utm_c != c]

There are no afilliates in the 3rd layer attracted by other afilliates from the 3rd layer:

In [8]:
for c in third_users.code:
    if third_users.utm_c.isin([c]).any():
        print(c)

Now we have three layers of affiliates: 
- <b>first_users</b> – were not attracted by any other affiliates
- <b>second_users</b> – were attracted by affiliates from the ``first_users``
- <b>third_users</b> – were attracted by affiliates from the ``second_users``

In [9]:
# displying first_users, second_users and third_users

first_users_styler = first_users.style.set_table_attributes("style='display:inline'")\
        .set_caption('1st Layer')

second_users_styler = second_users.style.set_table_attributes("style='display:inline'")\
        .set_caption('2nd Layer')

third_users_styler = third_users.style.set_table_attributes("style='display:inline'")\
        .set_caption('3rd Layer')

display_html(
    first_users_styler._repr_html_()+
    second_users_styler._repr_html_()+
    third_users_styler._repr_html_(), 
    raw=True)

,user_id,utm_c,code
0,d891c8305a,9cd0f2632,73a24f3d1
1,f94d3de761,afd8c7e77,0f87d693a
2,b1a6cf0230,8354af4ab,41c191655
3,e7717637a4,85fc32ec2,155c55d39
4,d774d65c49,85fc32ec2,5907960e6
5,74a3befdc7,85fc32ec2,0895ec4d4
6,3ab26bd8b9,85fc32ec2,1f7fbefc5
7,7b4e24d30f,85fc32ec2,5e2ee070b
8,df7fe09b2f,85fc32ec2,f08bd9e68
9,9b11b0aefd,f7e06d176,926b90c2e
10,613794730e,0cb609871,214d38284
11,7ce6c0e4f4,a062531fc,4d54ab76b
12,6bf9270677,a062531fc,424d12b35
13,14819cea5e,d081d872b,61211c816
14,68acd1fe87,85fc32ec2,9007795d1
15,660fc26842,7357a3b38,1c831580c
16,54e9b120b8,85fc32ec2,b27623082
17,e8b0a5f539,85fc32ec2,5d7b5ab75
18,aad98c7c3a,b5cf0ed3d,986e66bc6
19,5802d4f027,cccbb2a3c,dffb3f842
20,8528fb8be3,d081d872b,a58962781
21,c8b4b840f4,9fc5dfe6a,19d5825d3
22,1413230be9,184a474ae,e751650d0
23,93aabc15e5,4b914016e,61aff12e1
24,9fba1f9392,4b914016e,a2077b4c3
25,158708223a,3cb56f41d,6d9efaf2d
26,ce913ea790,85fc32ec2,7765124bc
27,a8f9e6bfe7,6f1f940b8,497843f51
28,4b9df617c2,d081d872b,339e6f5be
29,a12f7b9ea8,2b81c53e4,90dd5c735
30,dcd784e415,eca1ab5fb,fa806172a
31,2b6a2f2ffb,6be72e180,031fcc410
32,a3b40935f1,6be72e180,1551d9f82
33,943404a6ae,6be72e180,e27420a22
34,b751b9b8e2,6be72e180,c5d1842aa
36,5bc6a59dd9,030491c3e,ae8760154
37,5f745a74ea,303e668b3,f4277ddbd
38,f4e89f0177,6be72e180,ec745e82e
39,cda664208a,f122ae4dd,c337b099d
40,dae750a4d7,303e668b3,2f78905ae
41,a005934325,d64f31b50,f4e9c252e
42,c52d9139a2,d3e01b427,07757b9ab
43,3048b89d61,3394d839b,ef0c58ab0
44,974ec16bbe,303e668b3,a70df2a80
45,99ba5c157b,b647ec41c,9c9b99a7d
46,f0d6224a85,e3e356381,bef3a999a
47,3edee82c4b,610340f2b,014c9fd03
48,09b2d849aa,3f0d1117e,b0d278ce5
49,a3ae3125fe,6be72e180,25f86d053
50,f852e0a44d,6be72e180,d201ed71e
51,6bd6b92b3a,6be72e180,9e6e7d2cd
52,74604fe09e,6be72e180,5365eee70
54,d455865764,2cfb647e1,4c40037fe
55,333a20733f,6be72e180,3488f3c53
56,c5227bc6ec,d3e01b427,5fdb686bd
57,af983a5bf8,e4696ad32,02bf670f8
58,ad02216348,cdec5d1a4,1c3bf578a
59,5866a635ad,66ccd6b7d,fdcd0cf84
60,1f2011f7fb,e3e356381,f7d65b08a
61,a7303e6ffd,20d2e9f45,c3e0637bf
62,b1a454c8d9,d3e01b427,747a091eb
64,254a9452a3,f4fd38ced,9f785089b
65,11aa052f97,403660af8,89c7d2692
66,76b9b5442f,6be72e180,3806c1655
67,e3ee45e088,707808efa,21b61da61
68,e5046651b6,44a0edb0e,f7a9b2665
69,c21151620f,6be72e180,e14cc3062
71,e7806e6aae,99f09fa89,61590dfd1
72,c51447b252,d3e01b427,170336aa4
74,e5a232e343,6be72e180,8d0b0b141
75,d71b834a2d,6be72e180,33af67d03
76,7158fc0aec,c80f9aaeb,6ad790e07
77,95cf9410d4,6be72e180,e1d512b1b
78,b3012cf3bc,2c629c84b,9a3fdb651
79,8feeb3c236,f7e06d176,423e97d08
80,4907b9bf1f,d3e01b427,40b5be4db
82,5e653ffd95,14309c77b,0ea9f0c34
84,81f6fc5bb2,c40973ccd,e06a77c44
85,5e07fc57ca,43522eab6,b55e4dd58
86,30f8ceee97,0a4bed04d,a18becaa6
87,7f350ab78b,2104c2146,81ca858b3
88,3e7600a77f,d970badd1,2815e208f
89,c632debf28,09316aaf4,1f76150a0
90,2a62bcdeda,e7a553136,65cc86713
91,823aa6ae54,09316aaf4,df6e105c5
92,e6028af9ba,6be72e180,7ba09440c
93,f974e2afec,f46ef7b6d,159bbf7bf
94,3861c9f604,3f0d1117e,08c00f931
95,bb3d53a6e2,3f0d1117e,6ddd3a0be
96,c9ad00007d,09316aaf4,501ddbf4c
97,96f303087b,6be72e180,65c7d4c16
98,e782a8f47d,d3e01b427,757ec949d
99,e4b413811b,7dde7f732,06199f4eb
101,9a4cfc94b8,6be72e180,ce1703683
102,9e8f12ecb5,27f96d78c,5bf86f0df
103,25a98aeafd,6be72e180,2196f1196
104,4021191b45,c097c5e62,7432ea077
105,e9140632ef,6be72e180,e515a9bbe
106,61fa133c79,df5c9de8f,fc295eea3
107,c5f0b63976,ed8504620,e8db10f8f
108,25638fff05,7bbc2bab3,51a6d898d
109,0199160a3b,6be72e180,928cc7ee0
110,772cf45b63,c68faee1b,c8a6bf692
111,88783b3e1c,6be72e180,f5f98151f
112,e13cffd9e0,c80f9aaeb,2eb2acb76
113,ab235fc8ef,6be72e180,f5eef8008
114,7bf14edc28,6be72e180,fcd06a335
115,020d1cb3a9,6be72e180,73990fcd1
116,3685ecdff4,6be72e180,e34c164ac
117,7a6c07eeec,6be72e180,7232f513f
118,2e37b22ecd,6be72e180,aed52de1e
119,cf219cfca6,6be72e180,a14828d99
120,174dab4633,cb0ecee68,1e45073bc
121,b25f2d61e1,14e4fd658,b675bc18c
122,9d35c1fc18,6be72e180,1a3738b87
123,73b03f19d7,6be72e180,531cda2dd
124,c8ef0cd707,6be72e180,fd92d4775
125,c949f200d5,e1c99f78e,c73760c22
126,321c56f428,6be72e180,7fc05ebfe
127,5f53698e47,aa9778d3f,3ced838b2
128,aee5137410,cd8cf75a9,a959a0510
129,9da3ef9af1,b62bda80c,fc298ae61
130,241975d5b1,6be72e180,e69bd8a87
131,f4cdfaf3a7,b97e49113,0b4a86794
132,cd00e72fa3,8bec9cd22,2779b4cf7
,user_id,utm_c,code
35,b0fd1d6f6f,1551d9f82,2e1ca1050
63,6f77ad82a7,014c9fd03,a870227b5
83,f0e3b2548a,014c9fd03,75b759c38
70,d20a2ac474,25f86d053,0c481c232
73,3f61a9c4bf,25f86d053,232ebe1b6
81,39a6f4629e,33af67d03,501d17e75
,user_id,utm_c,code
100,c1bbf85336,75b759c38,30a810afa
53,00143ea850,0c481c232,854a6c26b

According to the task, our company gets only 20% of the revenue, since 80% goes to drivers. 
Now let's create a column called ``clean_price``, where we put the result of ``(price - credit - to_pay)*0.2``

In [10]:
orders_clean = pd.read_csv('data/orders_task3.csv')
orders_clean['clean_price'] = (orders_clean.price - orders_clean.credit - orders_clean.to_pay)*0.2

# now we don't need columns price, credit and to pay, since information we need 
# is now in clean_price column

orders_clean.drop(['price', 'credit', 'to_pay', 's_at'], axis=1, inplace=True)

# merging users' df.utm_c

orders_clean = orders_clean.merge(users[['user_id', 'utm_c']], how='left').dropna()

In [11]:
# creating df with orders grouped by marketing source

orders_by_source = orders_clean.groupby('utm_c').agg({
        'order_id': 'count',
        'clean_price': 'sum',
    }).reset_index().rename(columns={
        'order_id': 'orders_attracted',
        'clean_price': 'money_attracted',
        'user_id': 'users_attracted'
    })

# creating m_source df with amount of users brought by every utm_c

m_source = users.groupby('utm_c').agg({'user_id': 'count'}).reset_index()

# meging m_source df with orders_by_source

orders_by_source = orders_by_source.merge(m_source, on='utm_c') \
    .rename(columns={'user_id': 'users_attracted'})

``orders_by_source`` displays how many users, money and orders were attracted by each utm_c:

In [12]:
orders_by_source.head()

       utm_c  orders_attracted  money_attracted  users_attracted
0  0001c0ab8                 7       391.070995               13
1  0004f3ec5                 3      1198.062379                4
2  000717305                 1       296.804272                1
3  000e3f679                 2       448.207215                1
4  00115f959                 3       646.166294                5

Next we are creating ``first_users_df``, ``second_users_df`` and ``third_users_df``, these dfs simply contain info about user ids, utm_cs, codes and amount of orders, money and users attracted by these user ids.

Will use right join, since if there are affiliates that didn't attract anybody, 
they anyway could bring money by themselves:

In [13]:
# creating dfs

first_users_df = pd.merge(orders_by_source, 
                          first_users, 
                          left_on='utm_c', 
                          right_on='code', 
                          how='right')\
    .drop(columns={'utm_c_x'})\
    .rename(columns={'utm_c_y': 'utm_c'})

second_users_df = pd.merge(orders_by_source, 
                          second_users, 
                          left_on='utm_c', 
                          right_on='code', 
                          how='right')\
    .drop(columns={'utm_c_x'})\
    .rename(columns={'utm_c_y': 'utm_c'})

third_users_df = pd.merge(orders_by_source, 
                          third_users, 
                          left_on='utm_c', 
                          right_on='code', 
                          how='right')\
    .drop(columns={'utm_c_x'})\
    .rename(columns={'utm_c_y': 'utm_c'})

# changing the order of the columns

order = [3,4,5,0,1,2] # setting the right order

first_users_df = first_users_df[[first_users_df.columns[i] for i in order]]
second_users_df = second_users_df[[second_users_df.columns[i] for i in order]]
third_users_df = third_users_df[[third_users_df.columns[i] for i in order]]

In [14]:
# displaying heads of dfs 

first_users_styler = first_users_df.head().style.set_table_attributes("style='display:inline'")\
        .set_caption('1st Layer')

second_users_styler = second_users_df.head().style.set_table_attributes("style='display:inline'")\
        .set_caption('2nd Layer')

third_users_styler = third_users_df.head().style.set_table_attributes("style='display:inline'")\
        .set_caption('3rd Layer')

display_html(
    first_users_styler._repr_html_()+
    second_users_styler._repr_html_()+
    third_users_styler._repr_html_(), 
    raw=True)

,user_id,utm_c,code,orders_attracted,money_attracted,users_attracted
0,3edee82c4b,610340f2b,014c9fd03,556.000000,117866.075608,357.000000
1,2b6a2f2ffb,6be72e180,031fcc410,3.000000,689.891129,3.000000
2,e4b413811b,7dde7f732,06199f4eb,1.000000,177.508714,10.000000
3,c52d9139a2,d3e01b427,07757b9ab,614.000000,269918.878103,367.000000
4,74a3befdc7,85fc32ec2,0895ec4d4,11.000000,2213.219451,19.000000
,user_id,utm_c,code,orders_attracted,money_attracted,users_attracted
0,d20a2ac474,25f86d053,0c481c232,91,24264.584328,59
1,3f61a9c4bf,25f86d053,232ebe1b6,1,387.071751,9
2,b0fd1d6f6f,1551d9f82,2e1ca1050,28,7495.713376,41
3,39a6f4629e,33af67d03,501d17e75,34,7798.593607,8
4,f0e3b2548a,014c9fd03,75b759c38,63,18608.654480,44
,user_id,utm_c,code,orders_attracted,money_attracted,users_attracted
0,00143ea850,0c481c232,854a6c26b,8.000000,4149.692424,1.000000
1,c1bbf85336,75b759c38,30a810afa,nan,nan,nan

In [15]:
# creating temp_orders df to find out the amount of total clean price, payed by users

temp_orders = orders.groupby('user_id').agg({
        'order_id': 'count',
        'price': 'sum',
        'credit': 'sum',
        'to_pay': 'sum'
    }).reset_index()

# evaluating total_clean_price for every user

temp_orders['clean_total_price'] = (temp_orders.price - temp_orders.credit - temp_orders.to_pay)*0.2

# removing price, credit, to_pay columns

temp_orders.drop(['price', 'credit', 'to_pay'], axis=1, inplace=True)

In [16]:
temp_orders.head()

      user_id  order_id  clean_total_price
0  00003f9413         2         445.486845
1  0000e3575c         1         249.889643
2  0005012710         1          53.128449
3  00067c7cff         2         553.326886
4  000781601d         1           0.000000

Now let's join information about amount and cost of orders made by users in first, second and third layers.

In case there is a row, which contains 5 NAs (all values except ``user_id, utm_c, code``), we remove it.

If at least 1 value exists (excluding ``user_id, utm_c, code``), we fill all NAs in this row with 0:

In [17]:
first_users_df.isna().sum()

user_id              0
utm_c                0
code                 0
orders_attracted    43
money_attracted     43
users_attracted     43
dtype: int64

In [18]:
first_users_df = first_users_df.merge(temp_orders[['user_id', 'order_id', 'clean_total_price']], how='left') \
    .rename(columns={
        'order_id': 'orders_made',
        'clean_total_price': 'money_earned'
    }).dropna(thresh=5).fillna(0)

second_users_df = second_users_df \
    .merge(temp_orders[['user_id', 'order_id', 'clean_total_price']], how='left') \
    .rename(columns={
        'order_id': 'orders_made',
        'clean_total_price': 'money_earned'
    }).dropna(thresh=5).fillna(0)

third_users_df = third_users_df \
    .merge(temp_orders[['user_id', 'order_id', 'clean_total_price']], how='left') \
    .rename(columns={
        'order_id': 'orders_made',
        'clean_total_price': 'money_earned'
    }).dropna(thresh=5).fillna(0)

In [19]:
# displaying heads of dfs 

first_users_styler = first_users_df.head().style.set_table_attributes("style='display:inline'")\
        .set_caption('1st Layer')

second_users_styler = second_users_df.head().style.set_table_attributes("style='display:inline'")\
        .set_caption('2nd Layer')

third_users_styler = third_users_df.head().style.set_table_attributes("style='display:inline'")\
        .set_caption('3rd Layer')

display_html(
    first_users_styler._repr_html_()+
    second_users_styler._repr_html_()+
    third_users_styler._repr_html_(), 
    raw=True)

,user_id,utm_c,code,orders_attracted,money_attracted,users_attracted,orders_made,money_earned
0,3edee82c4b,610340f2b,014c9fd03,556.000000,117866.075608,357.000000,190.000000,37916.000478
1,2b6a2f2ffb,6be72e180,031fcc410,3.000000,689.891129,3.000000,4.000000,2258.805626
2,e4b413811b,7dde7f732,06199f4eb,1.000000,177.508714,10.000000,13.000000,2854.705741
3,c52d9139a2,d3e01b427,07757b9ab,614.000000,269918.878103,367.000000,78.000000,39956.468399
4,74a3befdc7,85fc32ec2,0895ec4d4,11.000000,2213.219451,19.000000,77.000000,18925.114108
,user_id,utm_c,code,orders_attracted,money_attracted,users_attracted,orders_made,money_earned
0,d20a2ac474,25f86d053,0c481c232,91,24264.584328,59,69,14131.902985
1,3f61a9c4bf,25f86d053,232ebe1b6,1,387.071751,9,21,3833.921151
2,b0fd1d6f6f,1551d9f82,2e1ca1050,28,7495.713376,41,128,23243.740808
3,39a6f4629e,33af67d03,501d17e75,34,7798.593607,8,55,9461.663886
4,f0e3b2548a,014c9fd03,75b759c38,63,18608.654480,44,194,41643.470694
,user_id,utm_c,code,orders_attracted,money_attracted,users_attracted,orders_made,money_earned
0,00143ea850,0c481c232,854a6c26b,8.000000,4149.692424,1.000000,2.000000,-52.448716

Now we create df called ``a_tree``. 

This df represents the information about our affiliates. 

If affiliate was attreacted by other affiliate, it will be presented in our df.

In [20]:
# merging first_users_df with second_users_df 

a_tree = pd.merge(first_users_df, 
                    second_users_df, 
                    left_on='code', 
                    right_on='utm_c', 
                    how='left', 
                    suffixes=('_1', '_2'))

# adding suffix to colnames of third_users_df

third_users_df = third_users_df.add_suffix('_3')

# merging a_tree with third_users_df

a_tree = pd.merge(a_tree, 
         third_users_df, 
         left_on='code_2', 
         right_on='utm_c_3', 
         how='left').fillna(0)

# dropping unnecessary columns

a_tree = a_tree.drop(columns={
        'utm_c_1',
        'code_1',
        'utm_c_2',
        'code_2',
        'utm_c_3',
        'code_3',
    }, axis=1)

# mapping int on cols 1,3,4,7,9,10,13,15,16

for c in a_tree.iloc[:,[1,3,4,7,9,10,13,15,16]].columns:
    a_tree[c] = a_tree[c].map(int)
    
# rounding cols 2,5,8,11,14,17

for c in a_tree.iloc[:, [2,5,8,11,14,17]].columns:
    a_tree[c] = a_tree[c].round(2)

In [21]:
a_tree.head()

,user_id_1,orders_attracted_1,money_attracted_1,users_attracted_1,orders_made_1,money_earned_1,user_id_2,orders_attracted_2,money_attracted_2,users_attracted_2,orders_made_2,money_earned_2,user_id_3,orders_attracted_3,money_attracted_3,users_attracted_3,orders_made_3,money_earned_3
0,3edee82c4b,556,117866.08,357,190,37916.00,f0e3b2548a,63,18608.65,44,194,41643.47,0,0,0.0,0,0,0.0
1,3edee82c4b,556,117866.08,357,190,37916.00,6f77ad82a7,17,5888.69,23,54,9204.18,0,0,0.0,0,0,0.0
2,2b6a2f2ffb,3,689.89,3,4,2258.81,0,0,0.00,0,0,0.00,0,0,0.0,0,0,0.0
3,e4b413811b,1,177.51,10,13,2854.71,0,0,0.00,0,0,0.00,0,0,0.0,0,0,0.0
4,c52d9139a2,614,269918.88,367,78,39956.47,0,0,0.00,0,0,0.00,0,0,0.0,0,0,0.0

Let's see how many orders attracted affiliates from the 1st layer in total. 

It can be evaluated by summing up ``orders_attracted_1``, ``orders_attracted_2`` and ``orders_attracted_3``. 

We will do the same thing with money and users attracted by these affiliates.

In [22]:
a_tree_first = a_tree.groupby(['user_id_1', 
                'orders_attracted_1', 
                'money_attracted_1',
                'users_attracted_1',
                'orders_made_1',
                'money_earned_1'
               ]).agg({
    'orders_attracted_2': 'sum',
    'money_attracted_2': 'sum',
    'users_attracted_2': 'sum',
    'orders_attracted_3': 'sum',
    'money_attracted_3': 'sum',
    'users_attracted_3': 'sum' 
}).reset_index()

# adding columns orders_att_total, users_att_total, money_att_total

a_tree_first['orders_att_total'] = a_tree_first.orders_attracted_1 + a_tree_first.orders_attracted_2 + a_tree_first.orders_attracted_3
a_tree_first['users_att_total'] = a_tree_first.users_attracted_1 + a_tree_first.users_attracted_2 + a_tree_first.users_attracted_3
a_tree_first['money_att_total'] = a_tree_first.money_attracted_1 + a_tree_first.money_attracted_2 + a_tree_first.money_attracted_3

In [23]:
a_tree_first.head()

,user_id_1,orders_attracted_1,money_attracted_1,users_attracted_1,orders_made_1,money_earned_1,orders_attracted_2,money_attracted_2,users_attracted_2,orders_attracted_3,money_attracted_3,users_attracted_3,orders_att_total,users_att_total,money_att_total
0,0199160a3b,1,-40.00,7,10,2240.98,0,0.0,0,0,0.0,0,1,7,-40.00
1,020d1cb3a9,3,-90.42,1,1,-40.00,0,0.0,0,0,0.0,0,3,1,-90.42
2,09b2d849aa,2,456.60,3,23,6031.08,0,0.0,0,0,0.0,0,2,3,456.60
3,11aa052f97,0,0.00,0,10,1361.46,0,0.0,0,0,0.0,0,0,0,0.00
4,1413230be9,0,0.00,0,7,2874.49,0,0.0,0,0,0.0,0,0,0,0.00

Dataframe ``a_tree_first`` consists of affiliates of the 1st layer.

If an affiliate was brought any other affiliate, we treat all the orders, money and users attracted by the second affiliate like they were attracted by the first affiliate.

In [24]:
# dropping unnecessary columns

a_tree_first = a_tree_first.drop(a_tree_first.columns[[1,2,3,6,7,8,9,10,11,12]], axis=1) \
    .rename(columns={
    'user_id_1': 'user_id',
    'orders_made_1': 'orders_made',
    'money_earned_1': 'money_earned'
})

# creating money_earned_total column which is the sum of money_earned and money_att_total

a_tree_first['money_earned_total'] = a_tree_first.money_earned + a_tree_first.money_att_total

# creating impact column which represents the impact of every user's money_earned_total
# on the global money_earned_total:

a_tree_first['impact'] = ((a_tree_first.money_earned_total/a_tree_first.money_earned_total.sum())*100).round(2)

In [25]:
# sorting values by money_earned_total

a_tree_first.sort_values('money_earned_total', ascending=False)

,user_id,orders_made,money_earned,users_att_total,money_att_total,money_earned_total,impact
80,c52d9139a2,78,39956.47,367,269918.88,309875.35,14.78
62,a3ae3125fe,802,210044.33,99,90359.75,300404.08,14.33
61,a12f7b9ea8,538,192575.29,67,32135.01,224710.30,10.72
21,3edee82c4b,190,37916.00,424,142363.42,180279.42,8.60
89,ce913ea790,319,74872.13,0,0.00,74872.13,3.57
...,...,...,...,...,...,...,...
108,f852e0a44d,2,387.48,3,-100.00,287.48,0.01
58,9da3ef9af1,1,258.82,0,0.00,258.82,0.01
23,4907b9bf1f,2,158.13,0,0.00,158.13,0.01
53,96f303087b,1,94.24,0,0.00,94.24,0.00
1,020d1cb3a9,1,-40.00,1,-90.42,-130.42,-0.01

In [26]:
# evaluating money, earned by affiliates attracted by users a3ae3125fe

display(a_tree.loc[a_tree.user_id_1 == 'a3ae3125fe'].money_attracted_2.sum() + a_tree.loc[a_tree.user_id_1 == 'a3ae3125fe'].money_earned_2.sum())

42617.47

In [27]:
# checking if user 3edee82c4b brought any other affiliates: 

a_tree.loc[a_tree.user_id_1 == '3edee82c4b']

,user_id_1,orders_attracted_1,money_attracted_1,users_attracted_1,orders_made_1,money_earned_1,user_id_2,orders_attracted_2,money_attracted_2,users_attracted_2,orders_made_2,money_earned_2,user_id_3,orders_attracted_3,money_attracted_3,users_attracted_3,orders_made_3,money_earned_3
0,3edee82c4b,556,117866.08,357,190,37916.0,f0e3b2548a,63,18608.65,44,194,41643.47,0,0,0.0,0,0,0.0
1,3edee82c4b,556,117866.08,357,190,37916.0,6f77ad82a7,17,5888.69,23,54,9204.18,0,0,0.0,0,0,0.0

In [28]:
# evaluating money, earned by affiliates attracted by users 3edee82c4b

display(a_tree.loc[a_tree.user_id_1 == '3edee82c4b'].money_attracted_2.sum() + a_tree.loc[a_tree.user_id_1 == '3edee82c4b'].money_earned_2.sum())

75344.99

In [29]:
a_tree_first.sort_values('money_earned_total')

,user_id,orders_made,money_earned,users_att_total,money_att_total,money_earned_total,impact
1,020d1cb3a9,1,-40.00,1,-90.42,-130.42,-0.01
53,96f303087b,1,94.24,0,0.00,94.24,0.00
23,4907b9bf1f,2,158.13,0,0.00,158.13,0.01
58,9da3ef9af1,1,258.82,0,0.00,258.82,0.01
108,f852e0a44d,2,387.48,3,-100.00,287.48,0.01
...,...,...,...,...,...,...,...
89,ce913ea790,319,74872.13,0,0.00,74872.13,3.57
21,3edee82c4b,190,37916.00,424,142363.42,180279.42,8.60
61,a12f7b9ea8,538,192575.29,67,32135.01,224710.30,10.72
62,a3ae3125fe,802,210044.33,99,90359.75,300404.08,14.33
80,c52d9139a2,78,39956.47,367,269918.88,309875.35,14.78

In [30]:
a_tree.loc[a_tree.user_id_2 != 0]

,user_id_1,orders_attracted_1,money_attracted_1,users_attracted_1,orders_made_1,money_earned_1,user_id_2,orders_attracted_2,money_attracted_2,users_attracted_2,orders_made_2,money_earned_2,user_id_3,orders_attracted_3,money_attracted_3,users_attracted_3,orders_made_3,money_earned_3
0,3edee82c4b,556,117866.08,357,190,37916.00,f0e3b2548a,63,18608.65,44,194,41643.47,0,0,0.00,0,0,0.00
1,3edee82c4b,556,117866.08,357,190,37916.00,6f77ad82a7,17,5888.69,23,54,9204.18,0,0,0.00,0,0,0.00
9,a3b40935f1,165,35720.73,18,0,0.00,b0fd1d6f6f,28,7495.71,41,128,23243.74,0,0,0.00,0,0,0.00
21,a3ae3125fe,265,61558.41,30,802,210044.33,d20a2ac474,91,24264.58,59,69,14131.90,00143ea850,8,4149.69,1,2,-52.45
22,a3ae3125fe,265,61558.41,30,802,210044.33,3f61a9c4bf,1,387.07,9,21,3833.92,0,0,0.00,0,0,0.00
25,d71b834a2d,85,15284.29,34,92,14342.59,39a6f4629e,34,7798.59,8,55,9461.66,0,0,0.00,0,0,0.00

As we can see from the table above there are Top 4 users: 

1) <b>c52d9139a2</b> with 309 875.35 RUB (\~15% of the total income), where 39 956.47 RUB brought by him and 269 918.88 RUB by users he attracted. This user attracted 367 new users.

2) <b>a3ae3125fe</b> with 300 404.08 RUB (\~14% of the total income), where 210 044.33 RUB brought by him and 90 359.75 RUB by users he attracted. This user attracted 99 new users, among them are 2 affiliates: <u>d20a2ac474</u> and <u>3f61a9c4bf</u>, which brought him 42 617.47 RUB in total.

3) <b>a12f7b9ea8</b> with 224 710.30 RUB (\~11% of the total income), where 192 575.29 RUB brought by him and 32 135.01 RUB by users he attracted. This user attracted 67 new users.

4) <b>3edee82c4b</b> with 180 279.42 RUB (\~9% of the total income), where 37 916.00 RUB broght by him and 142 363.42 RUB by users he attracted. This user attracted 424 new users, among them there are 2 affiliates: <u>f0e3b2548a</u> and <u>6f77ad82a7</u>, which brought him 75 344.99 RUB in total.

Top 5 "worst" affiliates:

1) <b>020d1cb3a9</b>. This affiliate still didn't pay for his ride and brought just 1 users, which also still didn't pay for his ride.

2) <b>96f303087b</b>. This affiliate made just 1 order, brought 94,24 RUB and didn't attract anybody.

3) <b>4907b9bf1f</b>. This affiliate made just 2 orders, brought 158,13 RUB and didn't attract anybody.

4) <b>9da3ef9af1</b>. This affiliate made just 1 order, brought 258,82 RUB and didn't attract anybody.

5) <b>f852e0a44d</b>. This affiliate made just 2 orders, brought 387,48 RUB and attracted 3 users, which still didn't pay for their rides.

We also can see, that affiliates of the 2nd layer performed better than some of the 1st layer => they didn' appear in Top 5 "worst" affiliates. 
There is affiliate of the 3rd layer, which perfomed better than some of the 1st layer, this affiliate, under id <u>00143ea850</u>, attracted 4 149,69 RUB for us, though we didn't earned directly from this affiliate.